"""Generates the daily results image via OpenAI image editing API (gpt-image-1).

Flow: carrega o template salvo em src/assets/daily_template.png,
envia para a API de edição da OpenAI com um prompt pedindo para
trocar APENAS os números (data, PL, ALERTAS, GREEN, RED, ROI),
mantendo todo o layout, cores e decorações intactos.
"""
from __future__ import annotations

import base64
import io
from pathlib import Path

from loguru import logger

TEMPLATE_PATH = Path(__file__).parent.parent / "assets" / "daily_template.png"

_SIZE = "1024x1024"


def _build_prompt(
    date_label: str,
    pl: float,
    alertas: int,
    greens: int,
    reds: int,
    roi: float,
) -> str:
    pl_sign = "+" if pl >= 0 else ""
    pl_str = f"{pl_sign}{pl:.2f}u"
    pl_color = "bright green" if pl >= 0 else "red"
    return (
        "Edit ONLY the text numbers in this image. "
        "Keep the entire visual design, circuit board decorations, background, "
        "colors, fonts, layout, and all other elements exactly the same. "
        f"Make these changes: "
        f"(1) Date → '{date_label}'. "
        f"(2) Large central number → '{pl_str}' in {pl_color} color. "
        f"(3) ALERTAS value → '{alertas}'. "
        f"(4) GREEN value → '{greens}'. "
        f"(5) RED value → '{reds}'. "
        f"(6) ROI value → '{roi:.1f}%'. "
        "Do not change anything else."
    )


def _load_template() -> bytes:
    """Load and resize template to 1024x1024 PNG for OpenAI API."""
    if not TEMPLATE_PATH.exists():
        raise FileNotFoundError(
            f"Template não encontrado: {TEMPLATE_PATH}\n"
            "Salve a imagem de referência em src/assets/daily_template.png"
        )
    from PIL import Image
    img = Image.open(TEMPLATE_PATH).convert("RGBA").resize((1024, 1024))
    buf = io.BytesIO()
    img.save(buf, "PNG")
    return buf.getvalue()


async def generate_daily_image(
    date_label: str,
    pl: float,
    alertas: int,
    greens: int,
    reds: int,
    roi: float,
) -> bytes:
    """Return PNG bytes generated by OpenAI editing the daily report template.

    Args:
        date_label: "DD/MM/YYYY"
        pl: net profit/loss in units
        alertas: total non-suppressed alerts
        greens: winning alerts
        reds: losing alerts
        roi: ROI percentage (e.g. 26.4)
    """
    from openai import AsyncOpenAI
    from src.config import settings

    if not settings.openai_api_key:
        raise ValueError("OPENAI_API_KEY não configurada no .env")

    client = AsyncOpenAI(api_key=settings.openai_api_key)
    template_bytes = _load_template()
    prompt = _build_prompt(date_label, pl, alertas, greens, reds, roi)

    logger.info(f"[DailyImage] Chamando OpenAI gpt-image-2 edit — {date_label}")

    response = await client.images.edit(
        model="gpt-image-2",
        image=("daily_template.png", io.BytesIO(template_bytes), "image/png"),
        prompt=prompt,
        n=1,
        size=_SIZE,
    )

    img_b64 = response.data[0].b64_json
    logger.info("[DailyImage] Imagem gerada com sucesso")
    return base64.b64decode(img_b64)
